name: "Terraform apply"

on:
  push:
    branches: ["folder-structured"]

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    run-on: ubuntu-latest
    steps:
      - name: Code pull
        uses: actions/checkout@v4

      - name: Get AWS creds
        uses: aws-action/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "1.7.0"
      
      - name: Initialize and apply terraform
        run: |
          terraform init
          #terraform plan -no-color -out=tfplan
          #terraform apply -input=false tfplan
          terraform apply -input=false -auto-approve